apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: dockerkube-deployment-k8s
spec:
  selector:
    matchLabels:
      app: dockerkube-deployment-k8s
  replicas: 2  # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: dockerkube-deployment-k8s
    spec:
      containers:
      - name: dockerkube-deployment-k8s
        image: palak1605/dockerkubeimage:latest        # Image that will be used to containers in the cluster
        ports:
        - containerPort: 8081     # The port that the container is running on in the cluster
