apiVersion: v1
kind: Service
metadata:
  name: dockerkube-service-k8s
spec:
  type: NodePort
  selector:
    app: dockerkube-deployment-k8s
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31000
    protocol: TCP
    name: https


